CLASS zcl_04_class_ee18d DEFINITION INHERITING FROM ZCL_03_CLASS_EE18D
  PUBLIC

  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_04_class_ee18d IMPLEMENTATION.
ENDCLASS.
