CLASS zcl_05_class_ee18d DEFINITION INHERITING FROM zcl_04_class_ee18d
  PUBLIC

  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_05_class_ee18d IMPLEMENTATION.
ENDCLASS.
